pub mod collections;
pub mod types;
pub mod mana;
pub mod zones;
pub mod objects;
pub mod events;
pub mod state;
pub mod turn;
pub mod priority;
pub mod stack;
pub mod combat;
pub mod sba;
pub mod layers;
pub mod replacement;
pub mod triggers;
pub mod effects;
pub mod keywords;
pub mod targets;
pub mod actions;
pub mod format;
pub mod legal_actions;
pub mod registry;
pub mod engine;

// Re-export core types for convenience
pub use state::GameState;
pub use actions::Action;
pub use engine::{step, EngineYield};
pub use format::{FormatConfig, MulliganRule};
pub use objects::{ObjectId, ObjectArena, GameObject};
pub use registry::CardRegistry;
pub use types::*;
