//! JOU — set module. Auto-created by land_cards.py; add a proper set summary when curating.
pub mod rotted_hulk;
pub mod pensive_minotaur;
pub mod bladetusk_boar;
pub mod bassara_tower_archer;
pub mod pharika_s_chosen;
pub mod reprisal;
pub mod revel_of_the_fallen_god;
pub mod feast_of_dreams;
pub mod countermand;
pub mod desecration_plague;
pub mod hubris;
pub mod ritual_of_the_returned;
pub mod pull_from_the_deep;
pub mod spiteful_blow;
pub mod rise_of_eagles;
pub mod deicide;
pub mod starfall;
pub mod spite_of_mogis;
