//! Bootstrap script for the verify-pipeline scratch slots.
//!
//! `src/generated/_scratch/` holds the volatile candidate files that
//! `arcana-gen::verify` overwrites per run. There are `1 +
//! N_SCRATCH_SLOTS` slots:
//!
//! * `candidate.rs`            — the single-slot path (`bakeoff`).
//! * `candidate_0..N-1.rs`     — the batched path (`verify_dir
//!   --batch K`): a whole chunk is written across distinct slots and
//!   verified with ONE `cargo check` + ONE `cargo test`, amortising
//!   cargo's per-invocation cost across the chunk instead of paying
//!   it per card.
//!
//! All slot files are gitignored (`candidate*.rs`), so on a fresh
//! clone they don't exist and `_scratch/mod.rs` (which `pub mod`s
//! every slot) wouldn't compile. This script makes the crate
//! self-bootstrapping: it (re)generates `_scratch/mod.rs` and writes
//! a `_noop` stub for any missing slot. Both writes are idempotent —
//! content-compared before writing — so steady-state builds don't
//! churn git or force downstream rebuilds. We deliberately do NOT
//! `rerun-if-changed` the slot files: verify overwrites them every
//! run and we don't want that to rebuild the world.

use std::path::Path;

/// Number of batch slots (`candidate_0..N-1`). The batched verify
/// chunk size is bounded by this. Every slot is a module always
/// compiled into `arcana-cards`; the files are trivial stubs at
/// rest, so a generous count is ~free and means fewer `cargo`
/// invocations on large runs (e.g. 2000 cards → ~16 chunks).
const N_SCRATCH_SLOTS: usize = 128;

const SCRATCH_DIR: &str = "src/generated/_scratch";

const STUB: &str = "//! Volatile scratch — overwritten by `arcana-gen::verify`.\n\
                    //! `arcana-cards/build.rs` writes this `_noop` placeholder on\n\
                    //! fresh clones so the crate compiles before verify runs.\n\
                    \n\
                    pub fn _noop() {}\n";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let dir = Path::new(SCRATCH_DIR);
    let _ = std::fs::create_dir_all(dir);

    // Slot names: the single-slot `candidate` plus the batch slots.
    let mut slots: Vec<String> = vec!["candidate".to_string()];
    slots.extend((0..N_SCRATCH_SLOTS).map(|i| format!("candidate_{i}")));

    for slug in &slots {
        let path = dir.join(format!("{slug}.rs"));
        if !path.exists() {
            std::fs::write(&path, STUB).expect("writing scratch stub");
        }
    }

    // Regenerate mod.rs (idempotent: only write if content differs).
    let mut modrs = String::new();
    modrs.push_str(
        "//! Volatile scratch space for `arcana-gen::verify`.\n\
         //!\n\
         //! GENERATED by `arcana-cards/build.rs` — do not hand-edit; change\n\
         //! `N_SCRATCH_SLOTS` in build.rs instead. Every `candidate*` module\n\
         //! is overwritten per verify run and is gitignored.\n\
         //!\n\
         //! `candidate` is the single-slot path; `candidate_0..N-1` are the\n\
         //! batched path (one `cargo check`/`cargo test` per chunk).\n\n",
    );
    modrs.push_str(&format!(
        "/// Number of batch slots (`candidate_0..N-1`). Single source of\n\
         /// truth for the batched verify chunk size.\n\
         pub const N_SCRATCH_SLOTS: usize = {N_SCRATCH_SLOTS};\n\n",
    ));
    modrs.push_str("pub mod candidate;\n");
    for i in 0..N_SCRATCH_SLOTS {
        modrs.push_str(&format!("pub mod candidate_{i};\n"));
    }

    let mod_path = dir.join("mod.rs");
    let current = std::fs::read_to_string(&mod_path).unwrap_or_default();
    if current != modrs {
        std::fs::write(&mod_path, modrs).expect("writing _scratch/mod.rs");
    }
}
