//! UND — set module. Auto-created by land_cards.py; add a proper set summary when curating.
pub mod awol;
pub mod duh;
pub mod emcee;
pub mod free_range_chicken;
pub mod johnny_combo_player;
pub mod flavor_judge;
pub mod old_guard;
pub mod timmy_power_gamer;
pub mod underdome;
pub mod b_o_b_bevy_of_beebles;
pub mod goblin_haberdasher;
pub mod infernius_spawnington_iii_esq;
pub mod syr_cadian_knight_owl;
pub mod boomstacker;
pub mod wall_of_fortune;
pub mod knight_of_the_hokey_pokey;
pub mod slaying_mantis;
pub mod b_i_n_g_o;
