//! SCG — set module. Auto-created by land_cards.py; add a proper set summary when curating.
pub mod wirewood_guardian;
pub mod long_term_plans;
pub mod goblin_war_strike;
pub mod dimensional_breach;
pub mod dispersal_shield;
pub mod aphetto_runecaster;
pub mod vengeful_dead;
pub mod kurgadon;
pub mod daru_spiritualist;
pub mod consumptive_goo;
pub mod bonethorn_valesk;
pub mod goblin_psychopath;
pub mod ark_of_blight;
pub mod pyrostatic_pillar;
pub mod dragon_shadow;
pub mod pemmin_s_aura;
pub mod dragon_fangs;
pub mod uncontrolled_infestation;
