#!/usr/bin/env python3
"""Regenerate `arcana-cards/src/register_all.rs`.

C1 standing-attestation support. The catalog is ~3,300 `register`
fns; only the 35-card `register_seed` was ever wired, so the rest
were compile-only (no test built them). This emits a single
`register_all(&mut CardRegistry) -> usize` that calls every catalog
card's `register`, so one regression test exercises the whole
catalog (every register body runs; the registry's duplicate-name
panic and interner invariants are continuously enforced).

Mechanical + idempotent: walks `src/<set>/mod.rs` for the authoritative
`pub mod <slug>;` lines (the same lines land_cards.py maintains),
preserving raw-identifier escaping (`pub mod r#override;` →
`r#override::register`). The `generated` staging module is excluded
(scratch, not catalog). Run after land_cards.py (or via it).
"""
from __future__ import annotations
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "arcana-cards" / "src"
LIB = SRC / "lib.rs"
OUT = SRC / "register_all.rs"
MOD_RE = re.compile(r"^\s*pub mod ((?:r#)?\w+)\s*;\s*$")


def sets_from_lib() -> list[str]:
    out = []
    for line in LIB.read_text().splitlines():
        m = MOD_RE.match(line)
        if not m:
            continue
        ident = m.group(1)
        if ident in ("generated", "register_all"):
            continue
        out.append(ident)
    return out


def slugs_for_set(set_ident: str) -> list[str]:
    bare = set_ident[2:] if set_ident.startswith("r#") else set_ident
    mod_rs = SRC / bare / "mod.rs"
    if not mod_rs.exists():
        return []
    slugs = []
    for line in mod_rs.read_text().splitlines():
        m = MOD_RE.match(line)
        if m:
            slugs.append(m.group(1))
    return slugs


def main() -> int:
    lines = [
        "//! AUTO-GENERATED by arcana-gen/scripts/gen_register_all.py — do",
        "//! not edit by hand. Regenerate after landing cards.",
        "//!",
        "//! [`register_all`] wires every catalog card's `register` into",
        "//! one call so the C1 standing test exercises the whole catalog",
        "//! (every register body runs; duplicate-name / interner",
        "//! invariants are continuously enforced, not one-shot).",
        "",
        "use arcana_core::registry::CardRegistry;",
        "",
        "/// Register every catalog card into `reg`. Returns the number",
        "/// of `register` calls made (one per catalog module).",
        "///",
        "/// Panics if two catalog cards share a name "
        "(`CardRegistry::register`",
        "/// invariant) — that is the defect this function exists to",
        "/// surface in the standing test.",
        "pub fn register_all(reg: &mut CardRegistry) -> usize {",
        "    let mut n = 0usize;",
    ]
    total = 0
    for s in sets_from_lib():
        slugs = slugs_for_set(s)
        if not slugs:
            continue
        lines.append(f"    // --- {s} ---")
        for slug in slugs:
            lines.append(f"    crate::{s}::{slug}::register(reg); n += 1;")
            total += 1
    lines += ["    n", "}", ""]
    OUT.write_text("\n".join(lines))
    # Ensure lib.rs declares the module (once, just before `generated`).
    lib = LIB.read_text()
    if re.search(r"^pub mod register_all;\s*$", lib, re.M) is None:
        anchor = "/// Staging area for arcana-gen card generations."
        decl = "pub mod register_all;\n\n"
        lib = lib.replace(anchor, decl + anchor, 1)
        LIB.write_text(lib)
    print(f"register_all.rs: wrote {total} register calls "
          f"across {len(sets_from_lib())} set modules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
