//! MM2 — set module. Auto-created by land_cards.py; add a proper set summary when curating.
pub mod sickle_ripper;
pub mod boros_swiftblade;
pub mod skyhunter_skirmisher;
pub mod simic_initiate;
pub mod hearthfire_hobgoblin;
pub mod ethercaste_knight;
pub mod terashi_s_grasp;
pub mod waking_nightmare;
pub mod spectral_procession;
pub mod otherworldly_journey;
pub mod grim_affliction;
pub mod celestial_purge;
pub mod spread_the_sickness;
pub mod wildfire;
pub mod sigil_blessing;
pub mod vapor_snag;
pub mod hurkyl_s_recall;
pub mod tribal_flames;
